language: node_js
node_js:
  - 12

cache: yarn

jobs:
  include:
    - stage: test
      script: yarn run test
    - stage: e2e
      if: branch = main
      script: yarn run end_to_end_test
stages:
  - name: test
    if: type = pull_request OR type = push
  - name: e2e
    if: type = push AND branch = main
addons:
  apt:
    packages:
      - libgconf-2-4
