version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    command: yarn run dev
    stdin_open: true
    tty: true

volumes:
  node_modules:
